--- #Install nginx with a custom index page, that replaces a variable with keyboard input when executing in ansible.
- hosts: '{{ myhosts }}'
  remote_user: ansible
  become: yes
  become_method: sudo
  gather_facts: yes
  connection: ssh
  tasks:
  - name: install nginx web server
    yum:
        name: nginx
        state: latest
  -name: enable and start the nginx service
  service:
      name: nginx
      enabled: yes
      state: restarted
