--- #Install nginx with a custom index page, that replaces a variable with keyboard input when executing in ansible.
- hosts: aws
  remote_user: ec2-user
  become: yes
  become_method: sudo
  gather_facts: yes
  connection: ssh
  vars_prompt:
  - name: "MY_CUSTOM_TEXT"
    prompt: "Input text"
    default: "Giorgio Balconi"
  tasks:
  - name: install nginx web server
    yum:
        name: nginx
        state: latest
    notify:
    - enable and start the nginx service
  - name: replaces the index.html file
    template: src=index.html dest=/usr/share/nginx/html/index.html
  handlers:
  - name: enable and start the nginx service
    service:
      name: nginx
      enabled: yes
      state: restarted
